# Standalone Moonraker; install its service normally (KIAUH or upstream installer).
[server]
host: 0.0.0.0
port: 7125
klippy_uds_address: /home/pi/printer_data/comms/klippy.sock

[file_manager]
enable_object_processing: True

[history]
[announcements]

[authorization]
cors_domains:
    http://app.fluidd.xyz
    https://app.fluidd.xyz
    https://my.mainsail.xyz
    http://my.mainsail.xyz
    http://*.local
    http://*.lan
trusted_clients:
    127.0.0.1
    10.0.0.0/8
    127.0.0.0/8
    172.16.0.0/12
    192.168.1.0/24
    192.168.30.2/32
    192.168.20.0/24
    192.168.50.0/24
    FE80::/10
    ::1/128
    FD00::/8
